# .github/workflows/douban.yml
name: douban
on: 
  schedule:
  - cron: "0 2 */3 * *"
  workflow_dispatch:

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 222317686
        type: movie
        format: csv
        dir: ./doubanSync/douban
    
    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 222317686
        type: book
        format: csv
        dir: ./doubanSync/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './doubanSync/douban'
