# .github/workflows/douban.yml
name: douban
on: 
  schedule:
  - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 222317686
        type: movie
        format: csv
        dir: ./data/douban
    
    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 222317686
        type: book
        format: csv
        dir: ./data/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './data/douban'
